In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train = pd.read_pickle('train.pickle')
test = pd.read_pickle('test.pickle')

In [5]:
train

,Semana,Agencia_ID,Canal_ID,Ruta_SAK,Cliente_ID,Producto_ID,Venta_uni_hoy,Venta_hoy,Dev_uni_proxima,Dev_proxima,Demanda_uni_equil
0,3,1110,7,3301,15766,1212,3,25.14,0,0.00,3
1,3,1110,7,3301,15766,1216,4,33.52,0,0.00,4
2,3,1110,7,3301,15766,1238,4,39.32,0,0.00,4
3,3,1110,7,3301,15766,1240,4,33.52,0,0.00,4
4,3,1110,7,3301,15766,1242,3,22.92,0,0.00,3
5,3,1110,7,3301,15766,1250,5,38.20,0,0.00,5
6,3,1110,7,3301,15766,1309,3,20.28,0,0.00,3
7,3,1110,7,3301,15766,3894,6,56.10,0,0.00,6
8,3,1110,7,3301,15766,4085,4,24.60,0,0.00,4
9,3,1110,7,3301,15766,5310,6,31.68,0,0.00,6
10,3,1110,7,3301,15766,30531,8,62.24,0,0.00,8
11,3,1110,7,3301,15766,30548,4,21.52,0,0.00,4
12,3,1110,7,3301,15766,30571,12,75.00,0,0.00,12
13,3,1110,7,3301,15766,31309,7,43.75,0,0.00,7
14,3,1110,7,3301,15766,31506,10,62.50,0,0.00,10
15,3,1110,7,3301,15766,32393,5,15.10,0,0.00,5
16,3,1110,7,3301,15766,32933,3,21.12,0,0.00,3
17,3,1110,7,3301,15766,32936,3,21.12,0,0.00,3
18,3,1110,7,3301,15766,34053,8,36.00,0,0.00,8
19,3,1110,7,3301,15766,35651,12,90.00,0,0.00,12
20,3,1110,7,3301,15766,37057,8,60.00,0,0.00,8
21,3,1110,7,3301,15766,41938,4,39.64,0,0.00,4
22,3,1110,7,3301,15766,42434,5,22.90,0,0.00,5
23,3,1110,7,3301,22926,1125,18,172.80,0,0.00,18
24,3,1110,7,3301,22926,42122,18,561.60,0,0.00,18
25,3,1110,7,3301,24080,2233,19,378.86,0,0.00,19
26,3,1110,7,3301,24080,42122,12,374.40,0,0.00,12
27,3,1110,7,3301,24695,1187,1,148.50,0,0.00,1
28,3,1110,7,3301,24695,2233,8,159.52,0,0.00,8
29,3,1110,7,3301,50379,1146,3,64.17,0,0.00,3
...,...,...,...,...,...,...,...,...,...,...,...
74180434,9,25759,1,5517,4483380,45112,5,63.75,0,0.00,5
74180435,9,25759,1,5517,4483753,32873,2,13.88,0,0.00,2
74180436,9,25759,1,5517,4483753,36164,3,49.80,2,33.20,1
74180437,9,25759,1,5517,4483753,36598,2,18.42,0,0.00,2
74180438,9,25759,1,5517,4488100,32815,2,14.94,0,0.00,2
74180439,9,25759,1,5517,4488100,32873,1,6.94,0,0.00,1
74180440,9,25759,1,5517,4488100,34226,1,9.26,0,0.00,1
74180441,9,25759,1,5517,4488100,37401,1,13.60,0,0.00,1
74180442,9,25759,1,5517,4488100,43040,3,18.96,0,0.00,3
74180443,9,25759,1,5517,4488100,45112,4,51.00,0,0.00,4
74180444,9,25759,1,5517,4488107,32815,2,14.94,0,0.00,2
74180445,9,25759,1,5517,4488107,32873,4,27.76,0,0.00,4
74180446,9,25759,1,5517,4488107,34226,4,37.04,0,0.00,4
74180447,9,25759,1,5517,4488107,40886,6,39.18,0,0.00,6
74180448,9,25759,1,5517,4488107,45112,1,12.75,0,0.00,1
74180449,9,25759,1,5517,4488482,32873,4,27.76,0,0.00,4
74180450,9,25759,1,5517,4488482,34226,2,18.52,0,0.00,2
74180451,9,25759,1,5517,4488482,36164,1,16.60,1,16.60,0
74180452,9,25759,1,5517,4488482,40886,3,19.59,0,0.00,3
74180453,9,25759,1,5517,4494351,37024,1,16.80,0,0.00,1
74180454,9,25759,1,5517,4504425,34255,3,50.40,0,0.00,3
74180455,9,25759,1,5517,4528866,3718,3,27.00,0,0.00,3
74180456,9,25759,1,5517,4528866,30694,2,18.54,0,0.00,2
74180457,9,25759,1,5517,4528866,32815,2,14.94,0,0.00,2
74180458,9,25759,1,5517,4528866,32861,3,18.60,0,0.00,3
74180459,9,25759,1,5517,4528866,32873,4,27.76,0,0.00,4
74180460,9,25759,1,5517,4528866,34226,4,37.04,0,0.00,4
74180461,9,25759,1,5517,4528866,45112,4,51.00,0,0.00,4
74180462,9,25759,1,5517,4547943,40217,3,26.94,3,26.94,0
74180463,9,25759,1,5517,4708097,43159,1,10.40,0,0.00,1

In [7]:
train["Venta_hoy"] = train["Venta_hoy"].astype('float32')
train["Dev_proxima"] = train["Dev_proxima"].astype('float32')